### ISSUE TITLE
Error for the input file

### ISSUE THREAD

**Issue by Lily-WL** [eead-csic-compbio/metagenome_Pfam_score#1]
Dear Sir,

Can you help to figure out the problem? When I input the file *.faa which is download from MG-RAST. The script feedback error. 

_[root@ts-rd350 metagenome_Pfam_score]# perl mebsv1.pl -input W1_350genecalling_coding.faa -type metagenomic
mebsv1.pl -input W1_350genecalling_coding.faa -type metagenomic -fdr 0.01 -comp 0

**# ERROR: cannot list W1_350genecalling_coding.faa**_

By the way, it is the same for the test file:

_[root@ts-rd350 metagenome_Pfam_score]# perl mebsv1.pl -input test_metagenomes/4511045.3_metagenome.faa -type metagenomic
mebsv1.pl -input test_metagenomes/4511045.3_metagenome.faa -type metagenomic -fdr 0.01 -comp 0

ERROR: cannot list test_metagenomes/4511045.3_metagenome.faa_

And this:
_[root@ts-rd350 metagenome_Pfam_score]# perl mebsv1.pl -input test_metagenomes/ -type metagenomic
mebsv1.pl -input test_metagenomes/ -type metagenomic -fdr 0.01 -comp 0

Computing Mean Size Length (MSL) ...
4440966.3_metagenome.faa MSL=175 MSLbin=150 4511045.3_metagenome.faa MSL=32 MSLbin=30

	sulfur	carbon	oxygen	iron	nitrogen	

4440966.3_metagenome.faa
Error: Unrecognized format, trying to open hmm file cycles/sulfur/my_Pfam.sulfur.hmm for reading.

#ERROR: failed to generate test_metagenomes//4440966.3_metagenome.faa.sulfur.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/carbon/my_Pfam.carbon.hmm for reading.

ERROR: failed to generate test_metagenomes//4440966.3_metagenome.faa.carbon.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/oxygen/my_Pfam.oxygen.hmm for reading.

ERROR: failed to generate test_metagenomes//4440966.3_metagenome.faa.oxygen.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/iron/my_Pfam.iron.hmm for reading.

# ERROR: failed to generate test_metagenomes//4440966.3_metagenome.faa.iron.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/nitrogen/my_Pfam.nitrogen.hmm for reading.

ERROR: failed to generate test_metagenomes//4440966.3_metagenome.faa.nitrogen.hmmsearch.tab
Use of uninitialized value $path in concatenation (.) or string at mebsv1.pl line 248.
Use of uninitialized value $path in concatenation (.) or string at mebsv1.pl line 249.
	NAIncorrect number of command line arguments.
Usage: hmmsearch [options] <query hmmfile> <target seqfile>

where most common options are:
  -h : show brief help on version and usage

To see more help on available options, do hmmsearch -h

sh:行1: .hmmsearch.tab: 未找到命令
sh:行2: .hmm: 未找到命令
Unsuccessful stat on filename containing newline at mebsv1.pl line 253.
# ERROR: failed to generate test_metagenomes//4440966.3_metagenome.faa.
.hmmsearch.tab
	NA
4511045.3_metagenome.faa
Error: Unrecognized format, trying to open hmm file cycles/sulfur/my_Pfam.sulfur.hmm for reading.

ERROR: failed to generate test_metagenomes//4511045.3_metagenome.faa.sulfur.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/carbon/my_Pfam.carbon.hmm for reading.

ERROR: failed to generate test_metagenomes//4511045.3_metagenome.faa.carbon.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/oxygen/my_Pfam.oxygen.hmm for reading.

ERROR: failed to generate test_metagenomes//4511045.3_metagenome.faa.oxygen.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/iron/my_Pfam.iron.hmm for reading.

ERROR: failed to generate test_metagenomes//4511045.3_metagenome.faa.iron.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/nitrogen/my_Pfam.nitrogen.hmm for reading.

ERROR: failed to generate test_metagenomes//4511045.3_metagenome.faa.nitrogen.hmmsearch.tab
Use of uninitialized value $path in concatenation (.) or string at mebsv1.pl line 248.
Use of uninitialized value $path in concatenation (.) or string at mebsv1.pl line 249.
	NAIncorrect number of command line arguments.
Usage: hmmsearch [options] <query hmmfile> <target seqfile>

where most common options are:
  -h : show brief help on version and usage

To see more help on available options, do hmmsearch -h

sh:行1: .hmmsearch.tab: 未找到命令
sh:行2: .hmm: 未找到命令
Unsuccessful stat on filename containing newline at mebsv1.pl line 253.
# ERROR: failed to generate test_metagenomes//4511045.3_metagenome.faa.
.hmmsearch.tab
	NA_

**Comment by valdeanda** [comment]
Hi Lily, 
Since we did some  recent updates in the algorithm, can you please  do 
git pull in the mebs directory? Or download the newest version.?  
Once you've done that,  you need to move your metagenome from MG-RAST in to a new directory.
mebs.pl requires  a input directory, not a fasta file. 
That should fix the problem. 
Please let me know if everything worked well
 Val

**Comment by Lily-WL** [comment]
Dear Valdeanda,

I diid what you said, but the error still came.

[root@ts-rd350 metagenome_Pfam_score]# **git pull**
Already up-to-date.
[root@ts-rd350 metagenome_Pfam_score]# **perl mebsv1.pl -input test_metagenomes -type metagenomic**
mebsv1.pl -input test_metagenomes -type metagenomic -fdr 0.01 -comp 0

Computing Mean Size Length (MSL) ...
4440966.3_metagenome.faa MSL=175 MSLbin=150
4511045.3_metagenome.faa MSL=32 MSLbin=30

	sulfur	carbon	oxygen	iron	nitrogen	

4440966.3_metagenome.faa
Error: Unrecognized format, trying to open hmm file cycles/sulfur/my_Pfam.sulfur.hmm for reading.

ERROR: failed to generate test_metagenomes/4440966.3_metagenome.faa.sulfur.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/carbon/my_Pfam.carbon.hmm for reading.

ERROR: failed to generate test_metagenomes/4440966.3_metagenome.faa.carbon.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/oxygen/my_Pfam.oxygen.hmm for reading.
ERROR: failed to generate test_metagenomes/4440966.3_metagenome.faa.oxygen.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/iron/my_Pfam.iron.hmm for reading.

ERROR: failed to generate test_metagenomes/4440966.3_metagenome.faa.iron.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/nitrogen/my_Pfam.nitrogen.hmm for reading.

ERROR: failed to generate test_metagenomes/4440966.3_metagenome.faa.nitrogen.hmmsearch.tab
Use of uninitialized value $path in concatenation (.) or string at mebsv1.pl line 248.
Use of uninitialized value $path in concatenation (.) or string at mebsv1.pl line 249.
	NAIncorrect number of command line arguments.
Usage: hmmsearch [options] <query hmmfile> <target seqfile>

where most common options are:
  -h : show brief help on version and usage

To see more help on available options, do hmmsearch -h

sh:行1: .hmmsearch.tab: 未找到命令
sh:行2: .hmm: 未找到命令
Unsuccessful stat on filename containing newline at mebsv1.pl line 253.
ERROR: failed to generate test_metagenomes/4440966.3_metagenome.faa.
.hmmsearch.tab
	NA
4511045.3_metagenome.faa
Error: Unrecognized format, trying to open hmm file cycles/sulfur/my_Pfam.sulfur.hmm for reading.

ERROR: failed to generate test_metagenomes/4511045.3_metagenome.faa.sulfur.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/carbon/my_Pfam.carbon.hmm for reading.

ERROR: failed to generate test_metagenomes/4511045.3_metagenome.faa.carbon.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/oxygen/my_Pfam.oxygen.hmm for reading.

ERROR: failed to generate test_metagenomes/4511045.3_metagenome.faa.oxygen.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/iron/my_Pfam.iron.hmm for reading.

ERROR: failed to generate test_metagenomes/4511045.3_metagenome.faa.iron.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/nitrogen/my_Pfam.nitrogen.hmm for reading.

ERROR: failed to generate test_metagenomes/4511045.3_metagenome.faa.nitrogen.hmmsearch.tab
Use of uninitialized value $path in concatenation (.) or string at mebsv1.pl line 248.
Use of uninitialized value $path in concatenation (.) or string at mebsv1.pl line 249.
	NAIncorrect number of command line arguments.
Usage: hmmsearch [options] <query hmmfile> <target seqfile>

where most common options are:
  -h : show brief help on version and usage

To see more help on available options, do hmmsearch -h

sh:行1: .hmmsearch.tab: 未找到命令
sh:行2: .hmm: 未找到命令
Unsuccessful stat on filename containing newline at mebsv1.pl line 253.
# ERROR: failed to generate test_metagenomes/4511045.3_metagenome.faa.
.hmmsearch.tab
	NA

**Comment by valdeanda** [comment]
Hi Lily, I haven't updated the readme, sorry. Try with the mebs.pl script instead of mebsv1.pl
That should fix the problem
Let me know if that works for you 
Valerie

**Comment by Lily-WL** [comment]
[root@ts-rd350 metagenome_Pfam_score]# perl mebs.pl -input test_metagenomes/ -type metagenomic
mebs.pl -input test_metagenomes/ -type metagenomic -fdr 0.01 -comp 0

 Computing Mean Size Length (MSL) ...
 4440966.3_metagenome.faa MSL=175 MSLbin=150
 4511045.3_metagenome.faa MSL=32 MSLbin=30

	sulfur	carbon	oxygen	iron	nitrogen
4440966.3_metagenome.faa
Error: Unrecognized format, trying to open hmm file cycles/sulfur/my_Pfam.sulfur.hmm for reading.

ERROR: failed to generate test_metagenomes//4440966.3_metagenome.faa.sulfur.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/carbon/my_Pfam.carbon.hmm for reading.

ERROR: failed to generate test_metagenomes//4440966.3_metagenome.faa.carbon.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/oxygen/my_Pfam.oxygen.hmm for reading.

ERROR: failed to generate test_metagenomes//4440966.3_metagenome.faa.oxygen.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/iron/my_Pfam.iron.hmm for reading.

ERROR: failed to generate test_metagenomes//4440966.3_metagenome.faa.iron.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/nitrogen/my_Pfam.nitrogen.hmm for reading.

ERROR: failed to generate test_metagenomes//4440966.3_metagenome.faa.nitrogen.hmmsearch.tab
	NA
4511045.3_metagenome.faa
Error: Unrecognized format, trying to open hmm file cycles/sulfur/my_Pfam.sulfur.hmm for reading.

ERROR: failed to generate test_metagenomes//4511045.3_metagenome.faa.sulfur.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/carbon/my_Pfam.carbon.hmm for reading.

ERROR: failed to generate test_metagenomes//4511045.3_metagenome.faa.carbon.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/oxygen/my_Pfam.oxygen.hmm for reading.

ERROR: failed to generate test_metagenomes//4511045.3_metagenome.faa.oxygen.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/iron/my_Pfam.iron.hmm for reading.

ERROR: failed to generate test_metagenomes//4511045.3_metagenome.faa.iron.hmmsearch.tab
	NA
Error: Unrecognized format, trying to open hmm file cycles/nitrogen/my_Pfam.nitrogen.hmm for reading.

ERROR: failed to generate test_metagenomes//4511045.3_metagenome.faa.nitrogen.hmmsearch.tab
	NA

**Comment by valdeanda** [comment]
HI LILy
I just ran the same comand line and It worked well 
 perl mebs.pl -input test_metagenomes/ -type metagenomic 
````
 mebs.pl -input test_metagenomes/ -type metagenomic -fdr 0.01 -comp 0
````
 Computing Mean Size Length (MSL) ...
 4511045.3_metagenome.faa MSL=32 MSLbin=30
 4440966.3_metagenome.faa MSL=175 MSLbin=150

	sulfur	carbon	oxygen	iron	nitrogen
4511045.3_metagenome.faa	-2.295	1.790	5.412	2.745	13.024
4440966.3_metagenome.faa	5.817	8.804	1.178	4.579	11.697

Try the following:
Did you change the config file? That could cause problems because mebs will look for the corresponding files according to the paths in the config file. 
To avoid any problems, try the following: 

1) Clone the repository again, to make sure that everything is updated (I've already deleted the other script)
2)  Cd into the directory and run the command line 
```
perl mebs.pl -input test_metagenomes/ -type metagenomic
```
Let me know if that worked.

**Comment by Lily-WL** [comment]
Dear Valdeanda,

I downloaded the file and the error are the same. The time is long to get the file in China. My OS is Centos 7.

[root@ts-rd350 metagenome_Pfam_score]# perl mebs.pl -input test_metagenomes/ -type metagenomic 
mebs.pl -input test_metagenomes/ -type metagenomic -fdr 0.01 -comp 0

Computing Mean Size Length (MSL) ...
 4440966.3_metagenome.faa MSL=175 MSLbin=150
4511045.3_metagenome.faa MSL=32 MSLbin=30

	sulfur	carbon	oxygen	iron	nitrogen
4440966.3_metagenome.faa
Error: Unrecognized format, trying to open hmm file cycles/sulfur/my_Pfam.sulfur.hmm for reading.

....................

**Comment by valdeanda** [comment]
Hi Lyly, 
Did you already clone the repository?, The  error looks like an error that we already fixed. Please let me know all the steps that you did in order to see what's the problem. You have already installed hmmsearch right?
The -comp option should be empty (without the "0") 
Valerie

**Comment by Lily-WL** [comment]
I just git clone and have the file "metagenome_Pfam_score", then excute the script "`perl mebs.pl -input test_metagenomes/ -type metagenomic`" in this file.

And the `hmmsearch` can be called from any place, such as in /opt. You can see the output in the following.

`[root@ts-rd350 opt]# hmmsearch -h`
hmmsearch :: search profile(s) against a sequence database
HMMER 3.0 (March 2010); http://hmmer.org/
Copyright (C) 2010 Howard Hughes Medical Institute.
Freely distributed under the GNU General Public License (GPLv3).
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Usage: hmmsearch [options] <query hmmfile> <target seqfile>

where basic options are:
  -h : show brief help on version and usage

options directing output:
  -o <f>          : direct output to file <f>, not stdout
  -A <f>          : save multiple alignment of all hits to file <s>
  --tblout <f>    : save parseable table of per-sequence hits to file <s>
  --domtblout <f> : save parseable table of per-domain hits to file <s>
  --acc           : prefer accessions over names in output
  --noali         : don't output alignments, so output is smaller
  --notextw       : unlimit ASCII text output line width
  --textw <n>     : set max width of ASCII text output lines  [120]  (n>=120)

options controlling reporting thresholds:
  -E <x>     : report sequences <= this E-value threshold in output  [10.0]  (x>0)
  -T <x>     : report sequences >= this score threshold in output
  --domE <x> : report domains <= this E-value threshold in output  [10.0]  (x>0)
  --domT <x> : report domains >= this score cutoff in output

options controlling inclusion (significance) thresholds:
  --incE <x>    : consider sequences <= this E-value threshold as significant
  --incT <x>    : consider sequences >= this score threshold as significant
  --incdomE <x> : consider domains <= this E-value threshold as significant
  --incdomT <x> : consider domains >= this score threshold as significant

options controlling model-specific thresholding:
  --cut_ga : use profile's GA gathering cutoffs to set all thresholding
  --cut_nc : use profile's NC noise cutoffs to set all thresholding
  --cut_tc : use profile's TC trusted cutoffs to set all thresholding

options controlling acceleration heuristics:
  --max    : Turn all heuristic filters off (less speed, more power)
  --F1 <x> : Stage 1 (MSV) threshold: promote hits w/ P <= F1  [0.02]
  --F2 <x> : Stage 2 (Vit) threshold: promote hits w/ P <= F2  [1e-3]
  --F3 <x> : Stage 3 (Fwd) threshold: promote hits w/ P <= F3  [1e-5]
  --nobias : turn off composition bias filter

other expert options:
  --nonull2     : turn off biased composition score corrections
  -Z <x>        : set # of comparisons done, for E-value calculation
  --domZ <x>    : set # of significant seqs, for domain E-value calculation
  --seed <n>    : set RNG seed to <n> (if 0: one-time arbitrary seed)  [42]
  --tformat <s> : assert target <seqfile> is in format <s>>: no autodetection
  --cpu <n>     : number of parallel CPU workers to use for multithreads

**Comment by eead-csic-compbio** [comment]
Hi Lily-WL,
in case it helps, I just tried it in my system running hmmsearch 3.1b1 and it worked. So it might be that you need to update HMMER to 3.1b. Please try that and let us know how it goes,
Bruno

**Comment by eead-csic-compbio** [comment]
Hi again, I can confirm that those HMMs are not compatible with HMMER v3.0, since I was able to reproduce your error. So please, update to at least v3.1b1, cheers

**Comment by Lily-WL** [comment]
Thank you very much! The problem is fixed.
